In [ ]:
import numpy as np
from itertools import product

from stats_utils import generate_all_allocations, calculate_utilities, calculate_all_envy, max_nash_welfare, max_egalitarian_welfare, max_utilitarian_welfare



# Based on the provided valuation table
num_agents = 2  # Agents 0-4
num_items = 3   # Items 0-6

allocations = generate_all_allocations(num_agents, num_items)

# Generate all possible allocations
print(f"Generating all possible allocations for {num_agents} agents and {num_items} items...")
print(f"This will create {num_agents ** num_items} different allocations.")



Generating all possible allocations for 2 agents and 3 items...
This will create 8 different allocations.


In [1]:
# given a valuation table get the number of allocations that are envy free

with open('outputs/agents_2/items_3/gpt4o/zero_shot0/output_3.txt', 'r') as file:

    lines = file.readlines()
    start = lines.index('Valuation Table:\n')
    end = lines.index('Output:\n')
    valuation_table = lines[start+1:end]
    valuation_table = ''.join(valuation_table)
    valuation_table = np.fromstring(valuation_table.replace('[', '').replace(']', ''), sep=' ')
    valuation_table = valuation_table.reshape(num_agents, num_items)
    valuation_table = valuation_table.astype(int)


env = calculate_all_envy(valuation_table * len(allocations), allocations, num_agents, num_items)
env = np.array(env)
env_count = np.sum(env)
print(f"Number of allocations: {len(allocations)}")
print(f"Number of allocations that are envy free: {env_count}")

# get the max welfare (nash, utilitarian, egalitarian) of the allocations
welfare = calculate_utilities(allocations, valuation_table)


# get the max welfare (nash, utilitarian, egalitarian) of the allocations



print(f"Max Nash welfare: {max_nash_welfare(welfare)}")
print(f"Max Utilitarian welfare: {max_utilitarian_welfare(welfare)}")
print(f"Max Egalitarian welfare: {max_egalitarian_welfare(welfare)}")


NameError: name 'np' is not defined

Max Nash welfare: 2976
Max Utilitarian welfare: 158
Max Egalitarian welfare: 45


In [28]:
env = np.array(env)
# Check if all allocations are envy-free


In [33]:
allocations

array([[[1, 1, 1],
        [0, 0, 0]],

       [[1, 1, 0],
        [0, 0, 1]],

       [[1, 0, 1],
        [0, 1, 0]],

       [[1, 0, 0],
        [0, 1, 1]],

       [[0, 1, 1],
        [1, 0, 0]],

       [[0, 1, 0],
        [1, 0, 1]],

       [[0, 0, 1],
        [1, 1, 0]],

       [[0, 0, 0],
        [1, 1, 1]]])

In [31]:
env

array([[False, False, False, False, False, False,  True, False]])

In [29]:
# count where env == True
env_count = np.sum(env)

In [30]:
env_count

1

In [14]:
# count number of times envy is true
envy_count = 0
for i in range(len(env)):
    if env[i].all():
        envy_count += 1
print(f"Number of envy-free allocations: {envy_count}")

Number of envy-free allocations: 0


In [8]:
print(f"Number of envy-free allocations: {envy_free_count}")

from envy_freeness import calculate_envy

print(calculate_envy([valuation_table], [allocations[0]], 7,8))

Number of envy-free allocations: 1431
(array([[[  0,   0,   0,   0,   0,   0,   0],
        [328,   0,   0,   0,   0,   0,   0],
        [426,   0,   0,   0,   0,   0,   0],
        [400,   0,   0,   0,   0,   0,   0],
        [427,   0,   0,   0,   0,   0,   0],
        [303,   0,   0,   0,   0,   0,   0],
        [440,   0,   0,   0,   0,   0,   0]]]), array([[[   0, -541, -541, -541, -541, -541, -541],
        [ 328,    0,    0,    0,    0,    0,    0],
        [ 426,    0,    0,    0,    0,    0,    0],
        [ 400,    0,    0,    0,    0,    0,    0],
        [ 427,    0,    0,    0,    0,    0,    0],
        [ 303,    0,    0,    0,    0,    0,    0],
        [ 440,    0,    0,    0,    0,    0,    0]]]))
